on:
  pull_request:
    branches: [main, master]

name: Run Tests

jobs:
  run-tests:
    runs-on: linux-x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install --global @n8n/node-cli

      - name: Build
        run: n8n-node build
